[project]
name = "jev-secret-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.2.3",
    "typesafe-sdk>=0.6.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]

[tool.ruff]
target-version = "py313"
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
